export const list: string[] = [
    "html",
    "C",
    "Python",
    "HTML5",
    "css",
    "java",
    "javascript",
    "aws",
    "c++",
    "react",
    "typescript",
    "mern",
    "nodejs",
  ];